package htmlgo

var InlineTags = map[string]bool{
	"a":        true,
	"abbr":     true,
	"acronym":  true,
	"b":        true,
	"bdo":      true,
	"big":      true,
	"br":       true,
	"button":   true,
	"cite":     true,
	"code":     true,
	"dfn":      true,
	"em":       true,
	"i":        true,
	"img":      true,
	"input":    true,
	"kbd":      true,
	"label":    true,
	"map":      true,
	"object":   true,
	"output":   true,
	"q":        true,
	"samp":     true,
	"script":   true,
	"select":   true,
	"small":    true,
	"span":     true,
	"strong":   true,
	"sub":      true,
	"sup":      true,
	"textarea": true,
	"time":     true,
	"tt":       true,
	"var":      true,
}
